//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMCWindows.GuestPlayerServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResponse", Namespace="http://schemas.datacontract.org/2004/07/Service.Results")]
    [System.SerializableAttribute()]
    public partial class OperationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorKey {
            get {
                return this.ErrorKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorKeyField, value) != true)) {
                    this.ErrorKeyField = value;
                    this.RaisePropertyChanged("ErrorKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GuestPlayerServer.IGuestPlayerService")]
    public interface IGuestPlayerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestPlayerService/RegisterGuestPlayer", ReplyAction="http://tempuri.org/IGuestPlayerService/RegisterGuestPlayerResponse")]
        BMCWindows.GuestPlayerServer.OperationResponse RegisterGuestPlayer(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestPlayerService/RegisterGuestPlayer", ReplyAction="http://tempuri.org/IGuestPlayerService/RegisterGuestPlayerResponse")]
        System.Threading.Tasks.Task<BMCWindows.GuestPlayerServer.OperationResponse> RegisterGuestPlayerAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestPlayerService/LogoutGuestPlayer", ReplyAction="http://tempuri.org/IGuestPlayerService/LogoutGuestPlayerResponse")]
        BMCWindows.GuestPlayerServer.OperationResponse LogoutGuestPlayer(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestPlayerService/LogoutGuestPlayer", ReplyAction="http://tempuri.org/IGuestPlayerService/LogoutGuestPlayerResponse")]
        System.Threading.Tasks.Task<BMCWindows.GuestPlayerServer.OperationResponse> LogoutGuestPlayerAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGuestPlayerServiceChannel : BMCWindows.GuestPlayerServer.IGuestPlayerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuestPlayerServiceClient : System.ServiceModel.ClientBase<BMCWindows.GuestPlayerServer.IGuestPlayerService>, BMCWindows.GuestPlayerServer.IGuestPlayerService {
        
        public GuestPlayerServiceClient() {
        }
        
        public GuestPlayerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GuestPlayerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuestPlayerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuestPlayerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BMCWindows.GuestPlayerServer.OperationResponse RegisterGuestPlayer(string username) {
            return base.Channel.RegisterGuestPlayer(username);
        }
        
        public System.Threading.Tasks.Task<BMCWindows.GuestPlayerServer.OperationResponse> RegisterGuestPlayerAsync(string username) {
            return base.Channel.RegisterGuestPlayerAsync(username);
        }
        
        public BMCWindows.GuestPlayerServer.OperationResponse LogoutGuestPlayer(string username) {
            return base.Channel.LogoutGuestPlayer(username);
        }
        
        public System.Threading.Tasks.Task<BMCWindows.GuestPlayerServer.OperationResponse> LogoutGuestPlayerAsync(string username) {
            return base.Channel.LogoutGuestPlayerAsync(username);
        }
    }
}
