//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMCWindows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BMCWindows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request another code.
        /// </summary>
        public static string AccountRequestAnotherCode {
            get {
                return ResourceManager.GetString("AccountRequestAnotherCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account verification.
        /// </summary>
        public static string AccountVerification {
            get {
                return ResourceManager.GetString("AccountVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have attacked!.
        /// </summary>
        public static string AttackMade {
            get {
                return ResourceManager.GetString("AttackMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel verification.
        /// </summary>
        public static string CancelVerificationTitle {
            get {
                return ResourceManager.GetString("CancelVerificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePasswordLabelChange {
            get {
                return ResourceManager.GetString("ChangePasswordLabelChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ChangePasswordLabelConfirmPasswrod {
            get {
                return ResourceManager.GetString("ChangePasswordLabelConfirmPasswrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string ChangePasswordLabelCurrentPassword {
            get {
                return ResourceManager.GetString("ChangePasswordLabelCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string ChangePasswordLabelNewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordLabelNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the operation?.
        /// </summary>
        public static string Confirmation_ConfirmCancelation {
            get {
                return ResourceManager.GetString("Confirmation.ConfirmCancelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to expel the player {0}?.
        /// </summary>
        public static string ConfirmationBanPlayer {
            get {
                return ResourceManager.GetString("ConfirmationBanPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to invite {0}?.
        /// </summary>
        public static string ConfirmInvitation {
            get {
                return ResourceManager.GetString("ConfirmInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm invitation.
        /// </summary>
        public static string ConfirmInvitationTitle {
            get {
                return ResourceManager.GetString("ConfirmInvitationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm cancellation.
        /// </summary>
        public static string ConfirmMessageCancelTitle {
            get {
                return ResourceManager.GetString("ConfirmMessageCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to expel this player?.
        /// </summary>
        public static string ConfirmMessageContentBanPlayer {
            get {
                return ResourceManager.GetString("ConfirmMessageContentBanPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm expulsion.
        /// </summary>
        public static string ConfirmMessageTileBanPlayer {
            get {
                return ResourceManager.GetString("ConfirmMessageTileBanPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the password?.
        /// </summary>
        public static string ConfirmMessageUpdatePassword {
            get {
                return ResourceManager.GetString("ConfirmMessageUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change avatar.
        /// </summary>
        public static string EditProfileButtonChangeAvatar {
            get {
                return ResourceManager.GetString("EditProfileButtonChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string EditProfileLabelEditProfile {
            get {
                return ResourceManager.GetString("EditProfileLabelEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to add the player to the game, please try again.
        /// </summary>
        public static string Error_CantAddingPlayer {
            get {
                return ResourceManager.GetString("Error.CantAddingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to send the message, please try again later.
        /// </summary>
        public static string Error_CantSendMessages {
            get {
                return ResourceManager.GetString("Error.CantSendMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to send the position of your cards, please try again.
        /// </summary>
        public static string Error_CantSummitMatrix {
            get {
                return ResourceManager.GetString("Error.CantSummitMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem connecting to the server. Please check your internet connection or try again later..
        /// </summary>
        public static string Error_CommunicationError {
            get {
                return ResourceManager.GetString("Error.CommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are different, check them.
        /// </summary>
        public static string Error_DifferentPassword {
            get {
                return ResourceManager.GetString("Error.DifferentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is duplicated, please change it.
        /// </summary>
        public static string Error_DuplicateEmail {
            get {
                return ResourceManager.GetString("Error.DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a lobby registered with that name, please enter another name.
        /// </summary>
        public static string Error_DuplicateLobbyName {
            get {
                return ResourceManager.GetString("Error.DuplicateLobbyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is duplicated, please change it.
        /// </summary>
        public static string Error_DuplicateUsername {
            get {
                return ResourceManager.GetString("Error.DuplicateUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image is empty.
        /// </summary>
        public static string Error_EmptyImage {
            get {
                return ResourceManager.GetString("Error.EmptyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is currently unavailable. Do you want to return to the login page?.
        /// </summary>
        public static string Error_EndpointException {
            get {
                return ResourceManager.GetString("Error.EndpointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to update the profile, please try again later.
        /// </summary>
        public static string Error_ErrorWhileUpdatingProfile {
            get {
                return ResourceManager.GetString("Error.ErrorWhileUpdatingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to update your profile picture, please try again later..
        /// </summary>
        public static string Error_ErrorWhileUpdatingProfilePicture {
            get {
                return ResourceManager.GetString("Error.ErrorWhileUpdatingProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to kick the player.
        /// </summary>
        public static string Error_ExpelPlayer {
            get {
                return ResourceManager.GetString("Error.ExpelPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game already exists, please try another name.
        /// </summary>
        public static string Error_GameAlredyExists {
            get {
                return ResourceManager.GetString("Error.GameAlredyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place all your cards on the board.
        /// </summary>
        public static string Error_GameboardCardsNotPlaced {
            get {
                return ResourceManager.GetString("Error.GameboardCardsNotPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to start the game, please try again later.
        /// </summary>
        public static string Error_GameWontStart {
            get {
                return ResourceManager.GetString("Error.GameWontStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred on the server, please try again later.
        /// </summary>
        public static string Error_GeneralException {
            get {
                return ResourceManager.GetString("Error.GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, please try again later..
        /// </summary>
        public static string Error_GeneralMessage {
            get {
                return ResourceManager.GetString("Error.GeneralMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required image was not found.
        /// </summary>
        public static string Error_ImageNotFound {
            get {
                return ResourceManager.GetString("Error.ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password entered is incorrect, please correct it..
        /// </summary>
        public static string Error_IncorrectPassword {
            get {
                return ResourceManager.GetString("Error.IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect verification code..
        /// </summary>
        public static string Error_IncorrectVerificationCode {
            get {
                return ResourceManager.GetString("Error.IncorrectVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered biography is not valid, please correct it..
        /// </summary>
        public static string Error_InvalidBio {
            get {
                return ResourceManager.GetString("Error.InvalidBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email entered is not valid, please check it.
        /// </summary>
        public static string Error_InvalidEmail {
            get {
                return ResourceManager.GetString("Error.InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password entered is not correct, please correct it..
        /// </summary>
        public static string Error_InvalidLobbyPassword {
            get {
                return ResourceManager.GetString("Error.InvalidLobbyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password entered is incorrect, please check it..
        /// </summary>
        public static string Error_InvalidPassword {
            get {
                return ResourceManager.GetString("Error.InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information entered in the profile is not valid, please correct it.
        /// </summary>
        public static string Error_InvalidProfileData {
            get {
                return ResourceManager.GetString("Error.InvalidProfileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username entered is not valid, please check it.
        /// </summary>
        public static string Error_InvalidUsername {
            get {
                return ResourceManager.GetString("Error.InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code entered is incorrect.
        /// </summary>
        public static string Error_InvalidValidationCode {
            get {
                return ResourceManager.GetString("Error.InvalidValidationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lobby already exists, please try another name.
        /// </summary>
        public static string Error_LobbyAlreadyExists {
            get {
                return ResourceManager.GetString("Error.LobbyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lobby you are trying to enter is full.
        /// </summary>
        public static string Error_LobbyFull {
            get {
                return ResourceManager.GetString("Error.LobbyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lobby you are trying to enter was not found..
        /// </summary>
        public static string Error_LobbyNotFound {
            get {
                return ResourceManager.GetString("Error.LobbyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a card.
        /// </summary>
        public static string Error_NoCardSelected {
            get {
                return ResourceManager.GetString("Error.NoCardSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to notify the player, please try again.
        /// </summary>
        public static string Error_NotificacitionMissing {
            get {
                return ResourceManager.GetString("Error.NotificacitionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the host can perform this action.
        /// </summary>
        public static string Error_NotLobbyHost {
            get {
                return ResourceManager.GetString("Error.NotLobbyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a player.
        /// </summary>
        public static string Error_NotSelectedPlayer {
            get {
                return ResourceManager.GetString("Error.NotSelectedPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected player is not in the lobby.
        /// </summary>
        public static string Error_PlayerNotInLobby {
            get {
                return ResourceManager.GetString("Error.PlayerNotInLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player is not ready yet, please wait a moment.
        /// </summary>
        public static string Error_PlayerNotReady {
            get {
                return ResourceManager.GetString("Error.PlayerNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile not found.
        /// </summary>
        public static string Error_ProfileNotFound {
            get {
                return ResourceManager.GetString("Error.ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No score found for the selected player.
        /// </summary>
        public static string Error_ScoreNotFound {
            get {
                return ResourceManager.GetString("Error.ScoreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to send the code.
        /// </summary>
        public static string Error_SendCodeFailed {
            get {
                return ResourceManager.GetString("Error.SendCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while identifying the sender of the message, please try again..
        /// </summary>
        public static string Error_SenderNotFound {
            get {
                return ResourceManager.GetString("Error.SenderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Unavailable.
        /// </summary>
        public static string Error_ServerErrorTitle {
            get {
                return ResourceManager.GetString("Error.ServerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is having trouble completing your request, please try again later.
        /// </summary>
        public static string Error_SeverError {
            get {
                return ResourceManager.GetString("Error.SeverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to the server has timed out. Please try again later..
        /// </summary>
        public static string Error_TimeoutError {
            get {
                return ResourceManager.GetString("Error.TimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many resend attempts. Please try again in 1 minute..
        /// </summary>
        public static string Error_TooManyTries {
            get {
                return ResourceManager.GetString("Error.TooManyTries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed access.
        /// </summary>
        public static string Error_UnauthorizedAccess {
            get {
                return ResourceManager.GetString("Error.UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user you are trying to log in with is already logged in.
        /// </summary>
        public static string Error_UserAlreadyConnected {
            get {
                return ResourceManager.GetString("Error.UserAlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not logged in, please try again later.
        /// </summary>
        public static string Error_UserNotConnected {
            get {
                return ResourceManager.GetString("Error.UserNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user entered was not found, please check it.
        /// </summary>
        public static string Error_UserNotFound {
            get {
                return ResourceManager.GetString("Error.UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for your turn.
        /// </summary>
        public static string Error_WaitTurn {
            get {
                return ResourceManager.GetString("Error.WaitTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the first turn.
        /// </summary>
        public static string FirstTurn {
            get {
                return ResourceManager.GetString("FirstTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend request accepted successfully.
        /// </summary>
        public static string Friend_AcceptRequest {
            get {
                return ResourceManager.GetString("Friend.AcceptRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend request rejected successfully.
        /// </summary>
        public static string Friend_DeclinedRequest {
            get {
                return ResourceManager.GetString("Friend.DeclinedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friend.
        /// </summary>
        public static string FriendButtonAddFriend {
            get {
                return ResourceManager.GetString("FriendButtonAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove friend.
        /// </summary>
        public static string FriendButtonRemove {
            get {
                return ResourceManager.GetString("FriendButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send menssage.
        /// </summary>
        public static string FriendButtonSendMessage {
            get {
                return ResourceManager.GetString("FriendButtonSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string FriendLabelFriends {
            get {
                return ResourceManager.GetString("FriendLabelFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No friends found.
        /// </summary>
        public static string FriendLabelNoFriends {
            get {
                return ResourceManager.GetString("FriendLabelNoFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search friend.
        /// </summary>
        public static string FriendLabelSearchFriend {
            get {
                return ResourceManager.GetString("FriendLabelSearchFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show friends online.
        /// </summary>
        public static string FriendLabelShowOnline {
            get {
                return ResourceManager.GetString("FriendLabelShowOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string FriendRequestDecline {
            get {
                return ResourceManager.GetString("FriendRequestDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request.
        /// </summary>
        public static string FriendSendRequest {
            get {
                return ResourceManager.GetString("FriendSendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game over.
        /// </summary>
        public static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have clicked on cell: ({0},{1}) in your own dashboard.
        /// </summary>
        public static string Gameplay_Attack {
            get {
                return ResourceManager.GetString("Gameplay.Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy ´s board.
        /// </summary>
        public static string Gameplay_EnemyBoard {
            get {
                return ResourceManager.GetString("Gameplay.EnemyBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let´s play!.
        /// </summary>
        public static string Gameplay_Play {
            get {
                return ResourceManager.GetString("Gameplay.Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your board.
        /// </summary>
        public static string Gameplay_PlayerBoard {
            get {
                return ResourceManager.GetString("Gameplay.PlayerBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players in lobby.
        /// </summary>
        public static string GameplayPlayersInLobby {
            get {
                return ResourceManager.GetString("GameplayPlayersInLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shifts.
        /// </summary>
        public static string GameplayShifts {
            get {
                return ResourceManager.GetString("GameplayShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string GlobalButtonAccept {
            get {
                return ResourceManager.GetString("GlobalButtonAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string GlobalButtonBack {
            get {
                return ResourceManager.GetString("GlobalButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string GlobalButtonSaveChanges {
            get {
                return ResourceManager.GetString("GlobalButtonSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string GlobalButtonSearch {
            get {
                return ResourceManager.GetString("GlobalButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string GlobalExitButton {
            get {
                return ResourceManager.GetString("GlobalExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string GlobalLabelUser {
            get {
                return ResourceManager.GetString("GlobalLabelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GloblalButtonCancel {
            get {
                return ResourceManager.GetString("GloblalButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string GuestLogout {
            get {
                return ResourceManager.GetString("GuestLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string HomePageButtonEditProfile {
            get {
                return ResourceManager.GetString("HomePageButtonEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string HomePageButtonMatch {
            get {
                return ResourceManager.GetString("HomePageButtonMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string HomepagePlayers {
            get {
                return ResourceManager.GetString("HomepagePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string HomepageRequests {
            get {
                return ResourceManager.GetString("HomepageRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string HomepageSettings {
            get {
                return ResourceManager.GetString("HomepageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show cards.
        /// </summary>
        public static string HomePageShowCards {
            get {
                return ResourceManager.GetString("HomePageShowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected image exceeds the allowed size of 1 MB. Please choose another image..
        /// </summary>
        public static string ImageTooLarge {
            get {
                return ResourceManager.GetString("ImageTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography successfully updated.
        /// </summary>
        public static string Info_BioUpdated {
            get {
                return ResourceManager.GetString("Info.BioUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cards have been placed correctly.
        /// </summary>
        public static string Info_CardsPostionSent {
            get {
                return ResourceManager.GetString("Info.CardsPostionSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code sent successfully..
        /// </summary>
        public static string Info_CodeSentSuccesfully {
            get {
                return ResourceManager.GetString("Info.CodeSentSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game not found, please try again.
        /// </summary>
        public static string Info_GameNotFound {
            get {
                return ResourceManager.GetString("Info.GameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the game.
        /// </summary>
        public static string Info_GameStarted {
            get {
                return ResourceManager.GetString("Info.GameStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has been closed successfully.
        /// </summary>
        public static string Info_GuestLogOut {
            get {
                return ResourceManager.GetString("Info.GuestLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to send the invitation email.
        /// </summary>
        public static string Info_InvitationEmailFailed {
            get {
                return ResourceManager.GetString("Info.InvitationEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation email sent successfully.
        /// </summary>
        public static string Info_InvitationSuccessful {
            get {
                return ResourceManager.GetString("Info.InvitationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t send messages because you are not friends.
        /// </summary>
        public static string Info_NoAreFriends {
            get {
                return ResourceManager.GetString("Info.NoAreFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not enough players to start the game, please wait for a player to join.
        /// </summary>
        public static string Info_NotEnoughPlayer {
            get {
                return ResourceManager.GetString("Info.NotEnoughPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the host can start the game, please wait for them to do so.
        /// </summary>
        public static string Info_OnlyHostStart {
            get {
                return ResourceManager.GetString("Info.OnlyHostStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player has not finished placing their cards, please wait.
        /// </summary>
        public static string Info_PlayerDontSummitGameBoard {
            get {
                return ResourceManager.GetString("Info.PlayerDontSummitGameBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile picture updated successfully.
        /// </summary>
        public static string Info_ProfileImageUpdated {
            get {
                return ResourceManager.GetString("Info.ProfileImageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was sent successfully.
        /// </summary>
        public static string Info_RequestSentSuccesfully {
            get {
                return ResourceManager.GetString("Info.RequestSentSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending verification code....
        /// </summary>
        public static string Info_SendingCode {
            get {
                return ResourceManager.GetString("Info.SendingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your turn {0}.
        /// </summary>
        public static string Info_Turn {
            get {
                return ResourceManager.GetString("Info.Turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username updated successfully.
        /// </summary>
        public static string Info_UserUpdated {
            get {
                return ResourceManager.GetString("Info.UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct code.
        /// </summary>
        public static string Info_ValidationCodeCorrect {
            get {
                return ResourceManager.GetString("Info.ValidationCodeCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current players.
        /// </summary>
        public static string Lobby_CurrentPlayers {
            get {
                return ResourceManager.GetString("Lobby.CurrentPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join lobby.
        /// </summary>
        public static string Lobby_JoinLobby {
            get {
                return ResourceManager.GetString("Lobby.JoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the available lobbies.
        /// </summary>
        public static string Lobby_LoadError {
            get {
                return ResourceManager.GetString("Lobby.LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby name.
        /// </summary>
        public static string Lobby_LobbyName {
            get {
                return ResourceManager.GetString("Lobby.LobbyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max players.
        /// </summary>
        public static string Lobby_MaxPlayers {
            get {
                return ResourceManager.GetString("Lobby.MaxPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a lobby.
        /// </summary>
        public static string Lobby_NotSelectedLobby {
            get {
                return ResourceManager.GetString("Lobby.NotSelectedLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string LobbyJoinLobby {
            get {
                return ResourceManager.GetString("LobbyJoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LoginButtonLogin {
            get {
                return ResourceManager.GetString("LoginButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in as guest.
        /// </summary>
        public static string LogInButtonLogInAsGuest {
            get {
                return ResourceManager.GetString("LogInButtonLogInAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string LoginLabelForgotPassword {
            get {
                return ResourceManager.GetString("LoginLabelForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string LoginLabelUser {
            get {
                return ResourceManager.GetString("LoginLabelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginLaberlPassword {
            get {
                return ResourceManager.GetString("LoginLaberlPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string MarchPropertyButtonPrivate {
            get {
                return ResourceManager.GetString("MarchPropertyButtonPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string MarchPropertyButtonPublic {
            get {
                return ResourceManager.GetString("MarchPropertyButtonPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loser.
        /// </summary>
        public static string Match_Loser {
            get {
                return ResourceManager.GetString("Match.Loser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        public static string Match_Winner {
            get {
                return ResourceManager.GetString("Match.Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create match.
        /// </summary>
        public static string MatchButtonCreateMatch {
            get {
                return ResourceManager.GetString("MatchButtonCreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite friend.
        /// </summary>
        public static string MatchButtonInviteFriend {
            get {
                return ResourceManager.GetString("MatchButtonInviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join match.
        /// </summary>
        public static string MatchButtonJoinMatch {
            get {
                return ResourceManager.GetString("MatchButtonJoinMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string MatchButtonPlay {
            get {
                return ResourceManager.GetString("MatchButtonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start match.
        /// </summary>
        public static string MatchButtonStartMatch {
            get {
                return ResourceManager.GetString("MatchButtonStartMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaing cards.
        /// </summary>
        public static string MatchLabelCards {
            get {
                return ResourceManager.GetString("MatchLabelCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match name.
        /// </summary>
        public static string MatchLabelMatchName {
            get {
                return ResourceManager.GetString("MatchLabelMatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create match.
        /// </summary>
        public static string MatchPropertyButtonCreateMarch {
            get {
                return ResourceManager.GetString("MatchPropertyButtonCreateMarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match name.
        /// </summary>
        public static string MatchPropertyTextBoxMatchName {
            get {
                return ResourceManager.GetString("MatchPropertyTextBoxMatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string MatchPropertyTextBoxPassword {
            get {
                return ResourceManager.GetString("MatchPropertyTextBoxPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are empty or invalid fields, please check them .
        /// </summary>
        public static string MessageBoxEmptyFields {
            get {
                return ResourceManager.GetString("MessageBoxEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar successfully updated.
        /// </summary>
        public static string MessageInformationContentAvatarUpdated {
            get {
                return ResourceManager.GetString("MessageInformationContentAvatarUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match, password could not be updated.
        /// </summary>
        public static string MessageInformationContentDiferentPassword {
            get {
                return ResourceManager.GetString("MessageInformationContentDiferentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not meet security requirements, could not update password.
        /// </summary>
        public static string MessageInformationContentInvalidePassword {
            get {
                return ResourceManager.GetString("MessageInformationContentInvalidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player succesfully added.
        /// </summary>
        public static string MessageInformationContentPlayerAdded {
            get {
                return ResourceManager.GetString("MessageInformationContentPlayerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update profile, the user is repeated.
        /// </summary>
        public static string MessageInformationContentRepeatedUser {
            get {
                return ResourceManager.GetString("MessageInformationContentRepeatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been successfully updated.
        /// </summary>
        public static string MessageInformationContentUpdatePassword {
            get {
                return ResourceManager.GetString("MessageInformationContentUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password, unable to update password.
        /// </summary>
        public static string MessageInformationContentWrongPassword {
            get {
                return ResourceManager.GetString("MessageInformationContentWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile successfully updated.
        /// </summary>
        public static string MessageInformationLabelContentUpdateProfile {
            get {
                return ResourceManager.GetString("MessageInformationLabelContentUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated username.
        /// </summary>
        public static string MessageInformationLabelTitleRepeatUser {
            get {
                return ResourceManager.GetString("MessageInformationLabelTitleRepeatUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated.
        /// </summary>
        public static string MessageInformationLabelTitleUpdateProfile {
            get {
                return ResourceManager.GetString("MessageInformationLabelTitleUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar updated.
        /// </summary>
        public static string MessageInformationTitleAvatarUpdated {
            get {
                return ResourceManager.GetString("MessageInformationTitleAvatarUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player added.
        /// </summary>
        public static string MessageInformationTitlePlayerAdded {
            get {
                return ResourceManager.GetString("MessageInformationTitlePlayerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm expulsion.
        /// </summary>
        public static string MessageTitleBanPlayer {
            get {
                return ResourceManager.GetString("MessageTitleBanPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! that was close :D.
        /// </summary>
        public static string MissedAttack {
            get {
                return ResourceManager.GetString("MissedAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated successfully.
        /// </summary>
        public static string PasswordUpdated {
            get {
                return ResourceManager.GetString("PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string PlayerLabelLevel {
            get {
                return ResourceManager.GetString("PlayerLabelLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play time.
        /// </summary>
        public static string PlayerLabelPlaytime {
            get {
                return ResourceManager.GetString("PlayerLabelPlaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses.
        /// </summary>
        public static string PlayerLosses {
            get {
                return ResourceManager.GetString("PlayerLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string PlayerStatusOffline {
            get {
                return ResourceManager.GetString("PlayerStatusOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string PlayerStatusOnline {
            get {
                return ResourceManager.GetString("PlayerStatusOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string PlayerTooltipHours {
            get {
                return ResourceManager.GetString("PlayerTooltipHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins.
        /// </summary>
        public static string PlayerWins {
            get {
                return ResourceManager.GetString("PlayerWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUpButtonSignUp {
            get {
                return ResourceManager.GetString("SignUpButtonSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string SignUpLabelConfirmPassword {
            get {
                return ResourceManager.GetString("SignUpLabelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SignUpLabelEmail {
            get {
                return ResourceManager.GetString("SignUpLabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SignUpPasswordBoxPassword {
            get {
                return ResourceManager.GetString("SignUpPasswordBoxPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReRepeat password.
        /// </summary>
        public static string SignUpPasswordBoxRepeatPassword {
            get {
                return ResourceManager.GetString("SignUpPasswordBoxRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SignUpTextBoxEmail {
            get {
                return ResourceManager.GetString("SignUpTextBoxEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string SignUpTextBoxUser {
            get {
                return ResourceManager.GetString("SignUpTextBoxUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the first turn, wait your turn.
        /// </summary>
        public static string TurnInfo {
            get {
                return ResourceManager.GetString("TurnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent to [email_truncated] with a verification code. Please enter the code..
        /// </summary>
        public static string VerificationDescription {
            get {
                return ResourceManager.GetString("VerificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example card.
        /// </summary>
        public static string ViewCardsLabelCardDescription {
            get {
                return ResourceManager.GetString("ViewCardsLabelCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        public static string ViewCardsLabelCards {
            get {
                return ResourceManager.GetString("ViewCardsLabelCards", resourceCulture);
            }
        }
    }
}
