//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMCWindows.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BMCWindows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request another code.
        /// </summary>
        public static string AccountRequestAnotherCode {
            get {
                return ResourceManager.GetString("AccountRequestAnotherCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account verification.
        /// </summary>
        public static string AccountVerification {
            get {
                return ResourceManager.GetString("AccountVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string ChangePasswordLabelChange {
            get {
                return ResourceManager.GetString("ChangePasswordLabelChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        public static string ChangePasswordLabelConfirmPasswrod {
            get {
                return ResourceManager.GetString("ChangePasswordLabelConfirmPasswrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current password.
        /// </summary>
        public static string ChangePasswordLabelCurrentPassword {
            get {
                return ResourceManager.GetString("ChangePasswordLabelCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string ChangePasswordLabelNewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordLabelNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm cancellation.
        /// </summary>
        public static string ConfirmMessageCancelTitle {
            get {
                return ResourceManager.GetString("ConfirmMessageCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to expel this player?.
        /// </summary>
        public static string ConfirmMessageContentBanPlayer {
            get {
                return ResourceManager.GetString("ConfirmMessageContentBanPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm expulsion.
        /// </summary>
        public static string ConfirmMessageTileBanPlayer {
            get {
                return ResourceManager.GetString("ConfirmMessageTileBanPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to change the password?.
        /// </summary>
        public static string ConfirmMessageUpdatePassword {
            get {
                return ResourceManager.GetString("ConfirmMessageUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change avatar.
        /// </summary>
        public static string EditProfileButtonChangeAvatar {
            get {
                return ResourceManager.GetString("EditProfileButtonChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit profile.
        /// </summary>
        public static string EditProfileLabelEditProfile {
            get {
                return ResourceManager.GetString("EditProfileLabelEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add friend.
        /// </summary>
        public static string FriendButtonAddFriend {
            get {
                return ResourceManager.GetString("FriendButtonAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove friend.
        /// </summary>
        public static string FriendButtonRemove {
            get {
                return ResourceManager.GetString("FriendButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send menssage.
        /// </summary>
        public static string FriendButtonSendMessage {
            get {
                return ResourceManager.GetString("FriendButtonSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string FriendLabelFriends {
            get {
                return ResourceManager.GetString("FriendLabelFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No friends found.
        /// </summary>
        public static string FriendLabelNoFriends {
            get {
                return ResourceManager.GetString("FriendLabelNoFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search friend.
        /// </summary>
        public static string FriendLabelSearchFriend {
            get {
                return ResourceManager.GetString("FriendLabelSearchFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show friends online.
        /// </summary>
        public static string FriendLabelShowOnline {
            get {
                return ResourceManager.GetString("FriendLabelShowOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decline.
        /// </summary>
        public static string FriendRequestDecline {
            get {
                return ResourceManager.GetString("FriendRequestDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send request.
        /// </summary>
        public static string FriendSendRequest {
            get {
                return ResourceManager.GetString("FriendSendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players in lobby.
        /// </summary>
        public static string GameplayPlayesInLobby {
            get {
                return ResourceManager.GetString("GameplayPlayesInLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string GlobalButtonAccept {
            get {
                return ResourceManager.GetString("GlobalButtonAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string GlobalButtonBack {
            get {
                return ResourceManager.GetString("GlobalButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Changes.
        /// </summary>
        public static string GlobalButtonSaveChanges {
            get {
                return ResourceManager.GetString("GlobalButtonSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string GlobalButtonSearch {
            get {
                return ResourceManager.GetString("GlobalButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string GlobalExitButton {
            get {
                return ResourceManager.GetString("GlobalExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string GlobalLabelUser {
            get {
                return ResourceManager.GetString("GlobalLabelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string GloblalButtonCancel {
            get {
                return ResourceManager.GetString("GloblalButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string HomePageButtonEditProfile {
            get {
                return ResourceManager.GetString("HomePageButtonEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matches.
        /// </summary>
        public static string HomePageButtonMatch {
            get {
                return ResourceManager.GetString("HomePageButtonMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players.
        /// </summary>
        public static string HomepagePlayers {
            get {
                return ResourceManager.GetString("HomepagePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requests.
        /// </summary>
        public static string HomepageRequests {
            get {
                return ResourceManager.GetString("HomepageRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string HomepageSettings {
            get {
                return ResourceManager.GetString("HomepageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show cards.
        /// </summary>
        public static string HomePageShowCards {
            get {
                return ResourceManager.GetString("HomePageShowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join.
        /// </summary>
        public static string LobbyJoinLobby {
            get {
                return ResourceManager.GetString("LobbyJoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string LoginButtonLogin {
            get {
                return ResourceManager.GetString("LoginButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LogIn As guest.
        /// </summary>
        public static string LogInButtonLogInAsGuest {
            get {
                return ResourceManager.GetString("LogInButtonLogInAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot password?.
        /// </summary>
        public static string LoginLabelForgotPassword {
            get {
                return ResourceManager.GetString("LoginLabelForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string LoginLabelUser {
            get {
                return ResourceManager.GetString("LoginLabelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string LoginLaberlPassword {
            get {
                return ResourceManager.GetString("LoginLaberlPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private.
        /// </summary>
        public static string MarchPropertyButtonPrivate {
            get {
                return ResourceManager.GetString("MarchPropertyButtonPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Public.
        /// </summary>
        public static string MarchPropertyButtonPublic {
            get {
                return ResourceManager.GetString("MarchPropertyButtonPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create match.
        /// </summary>
        public static string MatchButtonCreateMatch {
            get {
                return ResourceManager.GetString("MatchButtonCreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite friend.
        /// </summary>
        public static string MatchButtonInviteFriend {
            get {
                return ResourceManager.GetString("MatchButtonInviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join match.
        /// </summary>
        public static string MatchButtonJoinMatch {
            get {
                return ResourceManager.GetString("MatchButtonJoinMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        public static string MatchButtonPlay {
            get {
                return ResourceManager.GetString("MatchButtonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start match.
        /// </summary>
        public static string MatchButtonStartMatch {
            get {
                return ResourceManager.GetString("MatchButtonStartMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remaing cards.
        /// </summary>
        public static string MatchLabelCards {
            get {
                return ResourceManager.GetString("MatchLabelCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match name:.
        /// </summary>
        public static string MatchLabelMatchName {
            get {
                return ResourceManager.GetString("MatchLabelMatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create match.
        /// </summary>
        public static string MatchPropertyButtonCreateMarch {
            get {
                return ResourceManager.GetString("MatchPropertyButtonCreateMarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match name.
        /// </summary>
        public static string MatchPropertyTextBoxMatchName {
            get {
                return ResourceManager.GetString("MatchPropertyTextBoxMatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string MatchPropertyTextBoxPassword {
            get {
                return ResourceManager.GetString("MatchPropertyTextBoxPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are empty fields, check them .
        /// </summary>
        public static string MessageBoxEmptyFields {
            get {
                return ResourceManager.GetString("MessageBoxEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avatar successfully updated.
        /// </summary>
        public static string MessageInformationContentAvatarUpdated {
            get {
                return ResourceManager.GetString("MessageInformationContentAvatarUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match, password could not be updated.
        /// </summary>
        public static string MessageInformationContentDiferentPassword {
            get {
                return ResourceManager.GetString("MessageInformationContentDiferentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password does not meet security requirements, could not update password.
        /// </summary>
        public static string MessageInformationContentInvalidePassword {
            get {
                return ResourceManager.GetString("MessageInformationContentInvalidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player succesfully added.
        /// </summary>
        public static string MessageInformationContentPlayerAdded {
            get {
                return ResourceManager.GetString("MessageInformationContentPlayerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot update profile, the user is repeated.
        /// </summary>
        public static string MessageInformationContentRepeatedUser {
            get {
                return ResourceManager.GetString("MessageInformationContentRepeatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password has been successfully updated.
        /// </summary>
        public static string MessageInformationContentUpdatePassword {
            get {
                return ResourceManager.GetString("MessageInformationContentUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong password, unable to update password.
        /// </summary>
        public static string MessageInformationContentWrongPassword {
            get {
                return ResourceManager.GetString("MessageInformationContentWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile successfully updated.
        /// </summary>
        public static string MessageInformationLabelContentUpdateProfile {
            get {
                return ResourceManager.GetString("MessageInformationLabelContentUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeated username.
        /// </summary>
        public static string MessageInformationLabelTitleRepeatUser {
            get {
                return ResourceManager.GetString("MessageInformationLabelTitleRepeatUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile updated.
        /// </summary>
        public static string MessageInformationLabelTitleUpdateProfile {
            get {
                return ResourceManager.GetString("MessageInformationLabelTitleUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avatar updated.
        /// </summary>
        public static string MessageInformationTitleAvatarUpdated {
            get {
                return ResourceManager.GetString("MessageInformationTitleAvatarUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player added.
        /// </summary>
        public static string MessageInformationTitlePlayerAdded {
            get {
                return ResourceManager.GetString("MessageInformationTitlePlayerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Level.
        /// </summary>
        public static string PlayerLabelLevel {
            get {
                return ResourceManager.GetString("PlayerLabelLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play time.
        /// </summary>
        public static string PlayerLabelPlaytime {
            get {
                return ResourceManager.GetString("PlayerLabelPlaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Losses.
        /// </summary>
        public static string PlayerLosses {
            get {
                return ResourceManager.GetString("PlayerLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offline.
        /// </summary>
        public static string PlayerStatusOffline {
            get {
                return ResourceManager.GetString("PlayerStatusOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Online.
        /// </summary>
        public static string PlayerStatusOnline {
            get {
                return ResourceManager.GetString("PlayerStatusOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hours.
        /// </summary>
        public static string PlayerTooltipHours {
            get {
                return ResourceManager.GetString("PlayerTooltipHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wins.
        /// </summary>
        public static string PlayerWins {
            get {
                return ResourceManager.GetString("PlayerWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up.
        /// </summary>
        public static string SignUpButtonSignUp {
            get {
                return ResourceManager.GetString("SignUpButtonSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        public static string SignUpLabelConfirmPassword {
            get {
                return ResourceManager.GetString("SignUpLabelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string SignUpLabelEmail {
            get {
                return ResourceManager.GetString("SignUpLabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string SignUpPasswordBoxPassword {
            get {
                return ResourceManager.GetString("SignUpPasswordBoxPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ReRepeat password.
        /// </summary>
        public static string SignUpPasswordBoxRepeatPassword {
            get {
                return ResourceManager.GetString("SignUpPasswordBoxRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string SignUpTextBoxEmail {
            get {
                return ResourceManager.GetString("SignUpTextBoxEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string SignUpTextBoxUser {
            get {
                return ResourceManager.GetString("SignUpTextBoxUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An email has been sent to [email_truncated] with a verification code. Please enter the code..
        /// </summary>
        public static string VerificationDescription {
            get {
                return ResourceManager.GetString("VerificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Example card.
        /// </summary>
        public static string ViewCardsLabelCardDescription {
            get {
                return ResourceManager.GetString("ViewCardsLabelCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cards.
        /// </summary>
        public static string ViewCardsLabelCards {
            get {
                return ResourceManager.GetString("ViewCardsLabelCards", resourceCulture);
            }
        }
    }
}
