//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMCWindows.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BMCWindows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request another code.
        /// </summary>
        public static string AccountRequestAnotherCode {
            get {
                return ResourceManager.GetString("AccountRequestAnotherCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account verification.
        /// </summary>
        public static string AccountVerification {
            get {
                return ResourceManager.GetString("AccountVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have attacked!.
        /// </summary>
        public static string AttackMade {
            get {
                return ResourceManager.GetString("AttackMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel verification.
        /// </summary>
        public static string CancelVerificationTitle {
            get {
                return ResourceManager.GetString("CancelVerificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string ChangePasswordLabelChange {
            get {
                return ResourceManager.GetString("ChangePasswordLabelChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        public static string ChangePasswordLabelConfirmPasswrod {
            get {
                return ResourceManager.GetString("ChangePasswordLabelConfirmPasswrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current password.
        /// </summary>
        public static string ChangePasswordLabelCurrentPassword {
            get {
                return ResourceManager.GetString("ChangePasswordLabelCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string ChangePasswordLabelNewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordLabelNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to cancel the operation?.
        /// </summary>
        public static string Confirmation_ConfirmCancelation {
            get {
                return ResourceManager.GetString("Confirmation.ConfirmCancelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to expel the player {0}?.
        /// </summary>
        public static string ConfirmationBanPlayer {
            get {
                return ResourceManager.GetString("ConfirmationBanPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to invite {0}?.
        /// </summary>
        public static string ConfirmInvitation {
            get {
                return ResourceManager.GetString("ConfirmInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm invitation.
        /// </summary>
        public static string ConfirmInvitationTitle {
            get {
                return ResourceManager.GetString("ConfirmInvitationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm cancellation.
        /// </summary>
        public static string ConfirmMessageCancelTitle {
            get {
                return ResourceManager.GetString("ConfirmMessageCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to expel this player?.
        /// </summary>
        public static string ConfirmMessageContentBanPlayer {
            get {
                return ResourceManager.GetString("ConfirmMessageContentBanPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm expulsion.
        /// </summary>
        public static string ConfirmMessageTileBanPlayer {
            get {
                return ResourceManager.GetString("ConfirmMessageTileBanPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to change the password?.
        /// </summary>
        public static string ConfirmMessageUpdatePassword {
            get {
                return ResourceManager.GetString("ConfirmMessageUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change avatar.
        /// </summary>
        public static string EditProfileButtonChangeAvatar {
            get {
                return ResourceManager.GetString("EditProfileButtonChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit profile.
        /// </summary>
        public static string EditProfileLabelEditProfile {
            get {
                return ResourceManager.GetString("EditProfileLabelEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to add the player to the game, please try again.
        /// </summary>
        public static string Error_CantAddingPlayer {
            get {
                return ResourceManager.GetString("Error.CantAddingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to send the message, please try again later.
        /// </summary>
        public static string Error_CantSendMessages {
            get {
                return ResourceManager.GetString("Error.CantSendMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to send the position of your cards, please try again.
        /// </summary>
        public static string Error_CantSummitMatrix {
            get {
                return ResourceManager.GetString("Error.CantSummitMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was a problem connecting to the server. Please check your internet connection or try again later..
        /// </summary>
        public static string Error_CommunicationError {
            get {
                return ResourceManager.GetString("Error.CommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords are different, check them.
        /// </summary>
        public static string Error_DifferentPassword {
            get {
                return ResourceManager.GetString("Error.DifferentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email is duplicated, please change it.
        /// </summary>
        public static string Error_DuplicateEmail {
            get {
                return ResourceManager.GetString("Error.DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already a lobby registered with that name, please enter another name.
        /// </summary>
        public static string Error_DuplicateLobbyName {
            get {
                return ResourceManager.GetString("Error.DuplicateLobbyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username is duplicated, please change it.
        /// </summary>
        public static string Error_DuplicateUsername {
            get {
                return ResourceManager.GetString("Error.DuplicateUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The image is empty.
        /// </summary>
        public static string Error_EmptyImage {
            get {
                return ResourceManager.GetString("Error.EmptyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to update the profile, please try again later.
        /// </summary>
        public static string Error_ErrorWhileUpdatingProfile {
            get {
                return ResourceManager.GetString("Error.ErrorWhileUpdatingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to update your profile picture, please try again later..
        /// </summary>
        public static string Error_ErrorWhileUpdatingProfilePicture {
            get {
                return ResourceManager.GetString("Error.ErrorWhileUpdatingProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to kick the player.
        /// </summary>
        public static string Error_ExpelPlayer {
            get {
                return ResourceManager.GetString("Error.ExpelPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The game already exists, please try another name.
        /// </summary>
        public static string Error_GameAlredyExists {
            get {
                return ResourceManager.GetString("Error.GameAlredyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Place all your cards on the board.
        /// </summary>
        public static string Error_GameboardCardsNotPlaced {
            get {
                return ResourceManager.GetString("Error.GameboardCardsNotPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to start the game, please try again later.
        /// </summary>
        public static string Error_GameWontStart {
            get {
                return ResourceManager.GetString("Error.GameWontStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred on the server, please try again later.
        /// </summary>
        public static string Error_GeneralException {
            get {
                return ResourceManager.GetString("Error.GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred, please try again later..
        /// </summary>
        public static string Error_GeneralMessage {
            get {
                return ResourceManager.GetString("Error.GeneralMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The required image was not found.
        /// </summary>
        public static string Error_ImageNotFound {
            get {
                return ResourceManager.GetString("Error.ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password entered is incorrect, please correct it..
        /// </summary>
        public static string Error_IncorrectPassword {
            get {
                return ResourceManager.GetString("Error.IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The entered biography is not valid, please correct it..
        /// </summary>
        public static string Error_InvalidBio {
            get {
                return ResourceManager.GetString("Error.InvalidBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email entered is not valid, please check it.
        /// </summary>
        public static string Error_InvalidEmail {
            get {
                return ResourceManager.GetString("Error.InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password entered is not correct, please correct it..
        /// </summary>
        public static string Error_InvalidLobbyPassword {
            get {
                return ResourceManager.GetString("Error.InvalidLobbyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password entered is incorrect, please check it..
        /// </summary>
        public static string Error_InvalidPassword {
            get {
                return ResourceManager.GetString("Error.InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information entered in the profile is not valid, please correct it.
        /// </summary>
        public static string Error_InvalidProfileData {
            get {
                return ResourceManager.GetString("Error.InvalidProfileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username entered is not valid, please check it.
        /// </summary>
        public static string Error_InvalidUsername {
            get {
                return ResourceManager.GetString("Error.InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The code entered is incorrect.
        /// </summary>
        public static string Error_InvalidValidationCode {
            get {
                return ResourceManager.GetString("Error.InvalidValidationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The lobby already exists, please try another name.
        /// </summary>
        public static string Error_LobbyAlreadyExists {
            get {
                return ResourceManager.GetString("Error.LobbyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The lobby you are trying to enter is full.
        /// </summary>
        public static string Error_LobbyFull {
            get {
                return ResourceManager.GetString("Error.LobbyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The lobby you are trying to enter was not found..
        /// </summary>
        public static string Error_LobbyNotFound {
            get {
                return ResourceManager.GetString("Error.LobbyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a card.
        /// </summary>
        public static string Error_NoCardSelected {
            get {
                return ResourceManager.GetString("Error.NoCardSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to notify the player, please try again.
        /// </summary>
        public static string Error_NotificacitionMissing {
            get {
                return ResourceManager.GetString("Error.NotificacitionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only the host can perform this action.
        /// </summary>
        public static string Error_NotLobbyHost {
            get {
                return ResourceManager.GetString("Error.NotLobbyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a player.
        /// </summary>
        public static string Error_NotSelectedPlayer {
            get {
                return ResourceManager.GetString("Error.NotSelectedPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected player is not in the lobby.
        /// </summary>
        public static string Error_PlayerNotInLobby {
            get {
                return ResourceManager.GetString("Error.PlayerNotInLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The player is not ready yet, please wait a moment.
        /// </summary>
        public static string Error_PlayerNotReady {
            get {
                return ResourceManager.GetString("Error.PlayerNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile not found.
        /// </summary>
        public static string Error_ProfileNotFound {
            get {
                return ResourceManager.GetString("Error.ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No score found for the selected player.
        /// </summary>
        public static string Error_ScoreNotFound {
            get {
                return ResourceManager.GetString("Error.ScoreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to send the code.
        /// </summary>
        public static string Error_SendCodeFailed {
            get {
                return ResourceManager.GetString("Error.SendCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while identifying the sender of the message, please try again..
        /// </summary>
        public static string Error_SenderNotFound {
            get {
                return ResourceManager.GetString("Error.SenderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The server is having trouble completing your request, please try again later.
        /// </summary>
        public static string Error_SeverError {
            get {
                return ResourceManager.GetString("Error.SeverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The connection to the server has timed out. Please try again later..
        /// </summary>
        public static string Error_TimeoutError {
            get {
                return ResourceManager.GetString("Error.TimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Many resend attempts. Please try again in 1 minute..
        /// </summary>
        public static string Error_TooManyTries {
            get {
                return ResourceManager.GetString("Error.TooManyTries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are not allowed access.
        /// </summary>
        public static string Error_UnauthorizedAccess {
            get {
                return ResourceManager.GetString("Error.UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user you are trying to log in with is already logged in.
        /// </summary>
        public static string Error_UserAlreadyConnected {
            get {
                return ResourceManager.GetString("Error.UserAlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user is not logged in, please try again later.
        /// </summary>
        public static string Error_UserNotConnected {
            get {
                return ResourceManager.GetString("Error.UserNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user entered was not found, please check it.
        /// </summary>
        public static string Error_UserNotFound {
            get {
                return ResourceManager.GetString("Error.UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wait for your turn.
        /// </summary>
        public static string Error_WaitTurn {
            get {
                return ResourceManager.GetString("Error.WaitTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have the first turn.
        /// </summary>
        public static string FirstTurn {
            get {
                return ResourceManager.GetString("FirstTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request accepted successfully.
        /// </summary>
        public static string Friend_AcceptRequest {
            get {
                return ResourceManager.GetString("Friend.AcceptRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request rejected successfully.
        /// </summary>
        public static string Friend_DeclinedRequest {
            get {
                return ResourceManager.GetString("Friend.DeclinedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add friend.
        /// </summary>
        public static string FriendButtonAddFriend {
            get {
                return ResourceManager.GetString("FriendButtonAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove friend.
        /// </summary>
        public static string FriendButtonRemove {
            get {
                return ResourceManager.GetString("FriendButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send menssage.
        /// </summary>
        public static string FriendButtonSendMessage {
            get {
                return ResourceManager.GetString("FriendButtonSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string FriendLabelFriends {
            get {
                return ResourceManager.GetString("FriendLabelFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No friends found.
        /// </summary>
        public static string FriendLabelNoFriends {
            get {
                return ResourceManager.GetString("FriendLabelNoFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search friend.
        /// </summary>
        public static string FriendLabelSearchFriend {
            get {
                return ResourceManager.GetString("FriendLabelSearchFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show friends online.
        /// </summary>
        public static string FriendLabelShowOnline {
            get {
                return ResourceManager.GetString("FriendLabelShowOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decline.
        /// </summary>
        public static string FriendRequestDecline {
            get {
                return ResourceManager.GetString("FriendRequestDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send request.
        /// </summary>
        public static string FriendSendRequest {
            get {
                return ResourceManager.GetString("FriendSendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have clicked on cell: ({0},{1}) in your own dashboard.
        /// </summary>
        public static string Gameplay_Attack {
            get {
                return ResourceManager.GetString("Gameplay.Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enemy ´s board.
        /// </summary>
        public static string Gameplay_EnemyBoard {
            get {
                return ResourceManager.GetString("Gameplay.EnemyBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Let´s play!.
        /// </summary>
        public static string Gameplay_Play {
            get {
                return ResourceManager.GetString("Gameplay.Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your board.
        /// </summary>
        public static string Gameplay_PlayerBoard {
            get {
                return ResourceManager.GetString("Gameplay.PlayerBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players in lobby.
        /// </summary>
        public static string GameplayPlayesInLobby {
            get {
                return ResourceManager.GetString("GameplayPlayesInLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shifts.
        /// </summary>
        public static string GameplayShifts {
            get {
                return ResourceManager.GetString("GameplayShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string GlobalButtonAccept {
            get {
                return ResourceManager.GetString("GlobalButtonAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string GlobalButtonBack {
            get {
                return ResourceManager.GetString("GlobalButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Changes.
        /// </summary>
        public static string GlobalButtonSaveChanges {
            get {
                return ResourceManager.GetString("GlobalButtonSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string GlobalButtonSearch {
            get {
                return ResourceManager.GetString("GlobalButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string GlobalExitButton {
            get {
                return ResourceManager.GetString("GlobalExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string GlobalLabelUser {
            get {
                return ResourceManager.GetString("GlobalLabelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string GloblalButtonCancel {
            get {
                return ResourceManager.GetString("GloblalButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        public static string GuestLogout {
            get {
                return ResourceManager.GetString("GuestLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string HomePageButtonEditProfile {
            get {
                return ResourceManager.GetString("HomePageButtonEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matches.
        /// </summary>
        public static string HomePageButtonMatch {
            get {
                return ResourceManager.GetString("HomePageButtonMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players.
        /// </summary>
        public static string HomepagePlayers {
            get {
                return ResourceManager.GetString("HomepagePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requests.
        /// </summary>
        public static string HomepageRequests {
            get {
                return ResourceManager.GetString("HomepageRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string HomepageSettings {
            get {
                return ResourceManager.GetString("HomepageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show cards.
        /// </summary>
        public static string HomePageShowCards {
            get {
                return ResourceManager.GetString("HomePageShowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Biography successfully updated.
        /// </summary>
        public static string Info_BioUpdated {
            get {
                return ResourceManager.GetString("Info.BioUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your cards have been placed correctly.
        /// </summary>
        public static string Info_CardsPostionSent {
            get {
                return ResourceManager.GetString("Info.CardsPostionSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code sent successfully..
        /// </summary>
        public static string Info_CodeSentSuccesfully {
            get {
                return ResourceManager.GetString("Info.CodeSentSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game not found, please try again.
        /// </summary>
        public static string Info_GameNotFound {
            get {
                return ResourceManager.GetString("Info.GameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Starting the game.
        /// </summary>
        public static string Info_GameStarted {
            get {
                return ResourceManager.GetString("Info.GameStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your session has been closed successfully.
        /// </summary>
        public static string Info_GuestLogOut {
            get {
                return ResourceManager.GetString("Info.GuestLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to send the invitation email.
        /// </summary>
        public static string Info_InvitationEmailFailed {
            get {
                return ResourceManager.GetString("Info.InvitationEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitation email sent successfully.
        /// </summary>
        public static string Info_InvitationSuccessful {
            get {
                return ResourceManager.GetString("Info.InvitationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can&apos;t send messages because you are not friends.
        /// </summary>
        public static string Info_NoAreFriends {
            get {
                return ResourceManager.GetString("Info.NoAreFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are not enough players to start the game, please wait for a player to join.
        /// </summary>
        public static string Info_NotEnoughPlayer {
            get {
                return ResourceManager.GetString("Info.NotEnoughPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only the host can start the game, please wait for them to do so.
        /// </summary>
        public static string Info_OnlyHostStart {
            get {
                return ResourceManager.GetString("Info.OnlyHostStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The player has not finished placing their cards, please wait.
        /// </summary>
        public static string Info_PlayerDontSummitGameBoard {
            get {
                return ResourceManager.GetString("Info.PlayerDontSummitGameBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile picture updated successfully.
        /// </summary>
        public static string Info_ProfileImageUpdated {
            get {
                return ResourceManager.GetString("Info.ProfileImageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The request was sent successfully.
        /// </summary>
        public static string Info_RequestSentSuccesfully {
            get {
                return ResourceManager.GetString("Info.RequestSentSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sending verification code....
        /// </summary>
        public static string Info_SendingCode {
            get {
                return ResourceManager.GetString("Info.SendingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is your turn {0}.
        /// </summary>
        public static string Info_Turn {
            get {
                return ResourceManager.GetString("Info.Turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username updated successfully.
        /// </summary>
        public static string Info_UserUpdated {
            get {
                return ResourceManager.GetString("Info.UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correct code.
        /// </summary>
        public static string Info_ValidationCodeCorrect {
            get {
                return ResourceManager.GetString("Info.ValidationCodeCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while loading the available lobbies.
        /// </summary>
        public static string Lobby_LoadError {
            get {
                return ResourceManager.GetString("Lobby.LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a lobby.
        /// </summary>
        public static string Lobby_NotSelectedLobby {
            get {
                return ResourceManager.GetString("Lobby.NotSelectedLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join.
        /// </summary>
        public static string LobbyJoinLobby {
            get {
                return ResourceManager.GetString("LobbyJoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string LoginButtonLogin {
            get {
                return ResourceManager.GetString("LoginButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in as guest.
        /// </summary>
        public static string LogInButtonLogInAsGuest {
            get {
                return ResourceManager.GetString("LogInButtonLogInAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot password?.
        /// </summary>
        public static string LoginLabelForgotPassword {
            get {
                return ResourceManager.GetString("LoginLabelForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string LoginLabelUser {
            get {
                return ResourceManager.GetString("LoginLabelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string LoginLaberlPassword {
            get {
                return ResourceManager.GetString("LoginLaberlPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private.
        /// </summary>
        public static string MarchPropertyButtonPrivate {
            get {
                return ResourceManager.GetString("MarchPropertyButtonPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Public.
        /// </summary>
        public static string MarchPropertyButtonPublic {
            get {
                return ResourceManager.GetString("MarchPropertyButtonPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create match.
        /// </summary>
        public static string MatchButtonCreateMatch {
            get {
                return ResourceManager.GetString("MatchButtonCreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite friend.
        /// </summary>
        public static string MatchButtonInviteFriend {
            get {
                return ResourceManager.GetString("MatchButtonInviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join match.
        /// </summary>
        public static string MatchButtonJoinMatch {
            get {
                return ResourceManager.GetString("MatchButtonJoinMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        public static string MatchButtonPlay {
            get {
                return ResourceManager.GetString("MatchButtonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start match.
        /// </summary>
        public static string MatchButtonStartMatch {
            get {
                return ResourceManager.GetString("MatchButtonStartMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remaing cards.
        /// </summary>
        public static string MatchLabelCards {
            get {
                return ResourceManager.GetString("MatchLabelCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match name:.
        /// </summary>
        public static string MatchLabelMatchName {
            get {
                return ResourceManager.GetString("MatchLabelMatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create match.
        /// </summary>
        public static string MatchPropertyButtonCreateMarch {
            get {
                return ResourceManager.GetString("MatchPropertyButtonCreateMarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match name.
        /// </summary>
        public static string MatchPropertyTextBoxMatchName {
            get {
                return ResourceManager.GetString("MatchPropertyTextBoxMatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string MatchPropertyTextBoxPassword {
            get {
                return ResourceManager.GetString("MatchPropertyTextBoxPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are empty or invalid fields, please check them .
        /// </summary>
        public static string MessageBoxEmptyFields {
            get {
                return ResourceManager.GetString("MessageBoxEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avatar successfully updated.
        /// </summary>
        public static string MessageInformationContentAvatarUpdated {
            get {
                return ResourceManager.GetString("MessageInformationContentAvatarUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match, password could not be updated.
        /// </summary>
        public static string MessageInformationContentDiferentPassword {
            get {
                return ResourceManager.GetString("MessageInformationContentDiferentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password does not meet security requirements, could not update password.
        /// </summary>
        public static string MessageInformationContentInvalidePassword {
            get {
                return ResourceManager.GetString("MessageInformationContentInvalidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player succesfully added.
        /// </summary>
        public static string MessageInformationContentPlayerAdded {
            get {
                return ResourceManager.GetString("MessageInformationContentPlayerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot update profile, the user is repeated.
        /// </summary>
        public static string MessageInformationContentRepeatedUser {
            get {
                return ResourceManager.GetString("MessageInformationContentRepeatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password has been successfully updated.
        /// </summary>
        public static string MessageInformationContentUpdatePassword {
            get {
                return ResourceManager.GetString("MessageInformationContentUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong password, unable to update password.
        /// </summary>
        public static string MessageInformationContentWrongPassword {
            get {
                return ResourceManager.GetString("MessageInformationContentWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile successfully updated.
        /// </summary>
        public static string MessageInformationLabelContentUpdateProfile {
            get {
                return ResourceManager.GetString("MessageInformationLabelContentUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeated username.
        /// </summary>
        public static string MessageInformationLabelTitleRepeatUser {
            get {
                return ResourceManager.GetString("MessageInformationLabelTitleRepeatUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile updated.
        /// </summary>
        public static string MessageInformationLabelTitleUpdateProfile {
            get {
                return ResourceManager.GetString("MessageInformationLabelTitleUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avatar updated.
        /// </summary>
        public static string MessageInformationTitleAvatarUpdated {
            get {
                return ResourceManager.GetString("MessageInformationTitleAvatarUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player added.
        /// </summary>
        public static string MessageInformationTitlePlayerAdded {
            get {
                return ResourceManager.GetString("MessageInformationTitlePlayerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm expulsion.
        /// </summary>
        public static string MessageTitleBanPlayer {
            get {
                return ResourceManager.GetString("MessageTitleBanPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oops! that was close :D.
        /// </summary>
        public static string MissedAttack {
            get {
                return ResourceManager.GetString("MissedAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password updated successfully.
        /// </summary>
        public static string PasswordUpdated {
            get {
                return ResourceManager.GetString("PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Level.
        /// </summary>
        public static string PlayerLabelLevel {
            get {
                return ResourceManager.GetString("PlayerLabelLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play time.
        /// </summary>
        public static string PlayerLabelPlaytime {
            get {
                return ResourceManager.GetString("PlayerLabelPlaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Losses.
        /// </summary>
        public static string PlayerLosses {
            get {
                return ResourceManager.GetString("PlayerLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offline.
        /// </summary>
        public static string PlayerStatusOffline {
            get {
                return ResourceManager.GetString("PlayerStatusOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Online.
        /// </summary>
        public static string PlayerStatusOnline {
            get {
                return ResourceManager.GetString("PlayerStatusOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hours.
        /// </summary>
        public static string PlayerTooltipHours {
            get {
                return ResourceManager.GetString("PlayerTooltipHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wins.
        /// </summary>
        public static string PlayerWins {
            get {
                return ResourceManager.GetString("PlayerWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up.
        /// </summary>
        public static string SignUpButtonSignUp {
            get {
                return ResourceManager.GetString("SignUpButtonSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        public static string SignUpLabelConfirmPassword {
            get {
                return ResourceManager.GetString("SignUpLabelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string SignUpLabelEmail {
            get {
                return ResourceManager.GetString("SignUpLabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string SignUpPasswordBoxPassword {
            get {
                return ResourceManager.GetString("SignUpPasswordBoxPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ReRepeat password.
        /// </summary>
        public static string SignUpPasswordBoxRepeatPassword {
            get {
                return ResourceManager.GetString("SignUpPasswordBoxRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string SignUpTextBoxEmail {
            get {
                return ResourceManager.GetString("SignUpTextBoxEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string SignUpTextBoxUser {
            get {
                return ResourceManager.GetString("SignUpTextBoxUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You don&apos;t have the first turn, wait your turn.
        /// </summary>
        public static string TurnInfo {
            get {
                return ResourceManager.GetString("TurnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An email has been sent to [email_truncated] with a verification code. Please enter the code..
        /// </summary>
        public static string VerificationDescription {
            get {
                return ResourceManager.GetString("VerificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Example card.
        /// </summary>
        public static string ViewCardsLabelCardDescription {
            get {
                return ResourceManager.GetString("ViewCardsLabelCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cards.
        /// </summary>
        public static string ViewCardsLabelCards {
            get {
                return ResourceManager.GetString("ViewCardsLabelCards", resourceCulture);
            }
        }
    }
}
