//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMCWindows.FriendServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/Service.Results")]
    [System.SerializableAttribute()]
    public partial class OperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorKey {
            get {
                return this.ErrorKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorKeyField, value) != true)) {
                    this.ErrorKeyField = value;
                    this.RaisePropertyChanged("ErrorKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FriendServer.IFriendshipService")]
    public interface IFriendshipService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendshipService/SendFriendRequestResponse")]
        BMCWindows.FriendServer.OperationResult SendFriendRequest(string senderUsername, string reciveUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendshipService/SendFriendRequestResponse")]
        System.Threading.Tasks.Task<BMCWindows.FriendServer.OperationResult> SendFriendRequestAsync(string senderUsername, string reciveUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/AcceptFriendRequest", ReplyAction="http://tempuri.org/IFriendshipService/AcceptFriendRequestResponse")]
        BMCWindows.FriendServer.OperationResult AcceptFriendRequest(int idRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/AcceptFriendRequest", ReplyAction="http://tempuri.org/IFriendshipService/AcceptFriendRequestResponse")]
        System.Threading.Tasks.Task<BMCWindows.FriendServer.OperationResult> AcceptFriendRequestAsync(int idRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/RejectFriendResponse", ReplyAction="http://tempuri.org/IFriendshipService/RejectFriendResponseResponse")]
        BMCWindows.FriendServer.OperationResult RejectFriendResponse(int idResponse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/RejectFriendResponse", ReplyAction="http://tempuri.org/IFriendshipService/RejectFriendResponseResponse")]
        System.Threading.Tasks.Task<BMCWindows.FriendServer.OperationResult> RejectFriendResponseAsync(int idResponse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/GetFriendList", ReplyAction="http://tempuri.org/IFriendshipService/GetFriendListResponse")]
        BMCWindows.FriendServer.OperationResult GetFriendList(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/GetFriendList", ReplyAction="http://tempuri.org/IFriendshipService/GetFriendListResponse")]
        System.Threading.Tasks.Task<BMCWindows.FriendServer.OperationResult> GetFriendListAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/GetFriendRequestList", ReplyAction="http://tempuri.org/IFriendshipService/GetFriendRequestListResponse")]
        BMCWindows.FriendServer.OperationResult GetFriendRequestList(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/GetFriendRequestList", ReplyAction="http://tempuri.org/IFriendshipService/GetFriendRequestListResponse")]
        System.Threading.Tasks.Task<BMCWindows.FriendServer.OperationResult> GetFriendRequestListAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFriendshipServiceChannel : BMCWindows.FriendServer.IFriendshipService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FriendshipServiceClient : System.ServiceModel.ClientBase<BMCWindows.FriendServer.IFriendshipService>, BMCWindows.FriendServer.IFriendshipService {
        
        public FriendshipServiceClient() {
        }
        
        public FriendshipServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FriendshipServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendshipServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendshipServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BMCWindows.FriendServer.OperationResult SendFriendRequest(string senderUsername, string reciveUsername) {
            return base.Channel.SendFriendRequest(senderUsername, reciveUsername);
        }
        
        public System.Threading.Tasks.Task<BMCWindows.FriendServer.OperationResult> SendFriendRequestAsync(string senderUsername, string reciveUsername) {
            return base.Channel.SendFriendRequestAsync(senderUsername, reciveUsername);
        }
        
        public BMCWindows.FriendServer.OperationResult AcceptFriendRequest(int idRequest) {
            return base.Channel.AcceptFriendRequest(idRequest);
        }
        
        public System.Threading.Tasks.Task<BMCWindows.FriendServer.OperationResult> AcceptFriendRequestAsync(int idRequest) {
            return base.Channel.AcceptFriendRequestAsync(idRequest);
        }
        
        public BMCWindows.FriendServer.OperationResult RejectFriendResponse(int idResponse) {
            return base.Channel.RejectFriendResponse(idResponse);
        }
        
        public System.Threading.Tasks.Task<BMCWindows.FriendServer.OperationResult> RejectFriendResponseAsync(int idResponse) {
            return base.Channel.RejectFriendResponseAsync(idResponse);
        }
        
        public BMCWindows.FriendServer.OperationResult GetFriendList(string username) {
            return base.Channel.GetFriendList(username);
        }
        
        public System.Threading.Tasks.Task<BMCWindows.FriendServer.OperationResult> GetFriendListAsync(string username) {
            return base.Channel.GetFriendListAsync(username);
        }
        
        public BMCWindows.FriendServer.OperationResult GetFriendRequestList(string username) {
            return base.Channel.GetFriendRequestList(username);
        }
        
        public System.Threading.Tasks.Task<BMCWindows.FriendServer.OperationResult> GetFriendRequestListAsync(string username) {
            return base.Channel.GetFriendRequestListAsync(username);
        }
    }
}
