//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMCWindows.ProfileServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/Service.Results")]
    [System.SerializableAttribute()]
    public partial class OperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorKey {
            get {
                return this.ErrorKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorKeyField, value) != true)) {
                    this.ErrorKeyField = value;
                    this.RaisePropertyChanged("ErrorKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileServer.IProfileService")]
    public interface IProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/UpdatePassword", ReplyAction="http://tempuri.org/IProfileService/UpdatePasswordResponse")]
        BMCWindows.ProfileServer.OperationResult UpdatePassword(string username, string newPassword, string oldPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/UpdatePassword", ReplyAction="http://tempuri.org/IProfileService/UpdatePasswordResponse")]
        System.Threading.Tasks.Task<BMCWindows.ProfileServer.OperationResult> UpdatePasswordAsync(string username, string newPassword, string oldPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/UpdateProfilePicture", ReplyAction="http://tempuri.org/IProfileService/UpdateProfilePictureResponse")]
        BMCWindows.ProfileServer.OperationResult UpdateProfilePicture(string username, byte[] imageBytes, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/UpdateProfilePicture", ReplyAction="http://tempuri.org/IProfileService/UpdateProfilePictureResponse")]
        System.Threading.Tasks.Task<BMCWindows.ProfileServer.OperationResult> UpdateProfilePictureAsync(string username, byte[] imageBytes, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/UpdateUsername", ReplyAction="http://tempuri.org/IProfileService/UpdateUsernameResponse")]
        BMCWindows.ProfileServer.OperationResult UpdateUsername(string currentUsername, string newUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/UpdateUsername", ReplyAction="http://tempuri.org/IProfileService/UpdateUsernameResponse")]
        System.Threading.Tasks.Task<BMCWindows.ProfileServer.OperationResult> UpdateUsernameAsync(string currentUsername, string newUsername);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileServiceChannel : BMCWindows.ProfileServer.IProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileServiceClient : System.ServiceModel.ClientBase<BMCWindows.ProfileServer.IProfileService>, BMCWindows.ProfileServer.IProfileService {
        
        public ProfileServiceClient() {
        }
        
        public ProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BMCWindows.ProfileServer.OperationResult UpdatePassword(string username, string newPassword, string oldPassword) {
            return base.Channel.UpdatePassword(username, newPassword, oldPassword);
        }
        
        public System.Threading.Tasks.Task<BMCWindows.ProfileServer.OperationResult> UpdatePasswordAsync(string username, string newPassword, string oldPassword) {
            return base.Channel.UpdatePasswordAsync(username, newPassword, oldPassword);
        }
        
        public BMCWindows.ProfileServer.OperationResult UpdateProfilePicture(string username, byte[] imageBytes, string fileName) {
            return base.Channel.UpdateProfilePicture(username, imageBytes, fileName);
        }
        
        public System.Threading.Tasks.Task<BMCWindows.ProfileServer.OperationResult> UpdateProfilePictureAsync(string username, byte[] imageBytes, string fileName) {
            return base.Channel.UpdateProfilePictureAsync(username, imageBytes, fileName);
        }
        
        public BMCWindows.ProfileServer.OperationResult UpdateUsername(string currentUsername, string newUsername) {
            return base.Channel.UpdateUsername(currentUsername, newUsername);
        }
        
        public System.Threading.Tasks.Task<BMCWindows.ProfileServer.OperationResult> UpdateUsernameAsync(string currentUsername, string newUsername) {
            return base.Channel.UpdateUsernameAsync(currentUsername, newUsername);
        }
    }
}
